/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Cars;
import Model.Fleet;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author priyankakuklani
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Fleet carFleet;

    public ViewJPanel(Fleet fleet) {
        initComponents();
        this.carFleet = fleet;
        //for(int i = 0; i < carFleet.getFleet().size(); i++)
        DefaultTableModel model = (DefaultTableModel) jFleetSummary.getModel();
        Object rowData[] = new Object[9];
        var carList = fleet.getFleet();
        Format f = new SimpleDateFormat("MM/dd/yy");
        for (int i = 0; i < carList.size(); i++) {
            var obj = carList.get(i);
            rowData[0] = obj.getCarID();
            rowData[1] = obj.getManufacturerName();
            rowData[2] = obj.getModelNumber();
            rowData[3] = obj.getMaxSeat();
            rowData[4] = obj.getRegistrationState();
            rowData[5] = obj.getVehicleNumber();
            rowData[6] = obj.getCurrentAvailabilityText();
            rowData[7] = obj.getCurrentAvailability() ? "" : f.format(obj.getDateFrom());
            rowData[8] = obj.getCity();
            model.addRow(rowData);
        }

        jTotalCars.setText(Integer.toString(this.carFleet.getCarCount()));
        jAvailCars.setText(Integer.toString(this.carFleet.getAvailableCarCount()));
        jUnavailCars.setText(Integer.toString(this.carFleet.getUnavailableCarCount()));
        jLastUpdateAt.setText(this.carFleet.getLastUpdateDate().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jAvailCars = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jUnavailCars = new javax.swing.JLabel();
        jRegNumber = new javax.swing.JTextField();
        jRegStateComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jModelNumber = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLastUpdateAt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCurrentlyAvailableChkBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jRegValidCheckBox = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jManufactureTxtField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jCurrCity = new javax.swing.JTextField();
        jManufactureYearTxtField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jFleetSummary = new javax.swing.JTable();
        jMinSeatCap = new javax.swing.JTextField();
        jTotalCars = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMaxSeatCap = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jSearchButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(604, 607));

        jLabel16.setText("Available Cars");

        jAvailCars.setText("jLabel17");

        jLabel19.setText("Unavailable Cars");

        jLabel8.setText("Registration Number");

        jUnavailCars.setText("jLabel17");

        jRegNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegNumberActionPerformed(evt);
            }
        });

        jRegStateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Alabama", "Alaska", "American Samoa", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Guam", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Minor Outlying Islands", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Northern Mariana Islands", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Puerto Rico", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "U.S. Virgin Islands", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming" }));
        jRegStateComboBox.setSelectedIndex(-1);
        jRegStateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegStateComboBoxActionPerformed(evt);
            }
        });

        jLabel9.setText("Model");

        jModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModelNumberActionPerformed(evt);
            }
        });

        jLabel17.setText("Fleet Last Updated On");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Search Criteria");

        jLastUpdateAt.setText("jLabel17");

        jLabel2.setText("Currently Available");

        jCurrentlyAvailableChkBox.setSelected(true);
        jCurrentlyAvailableChkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCurrentlyAvailableChkBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Make");

        jLabel11.setText("Registration Valid");

        jRegValidCheckBox.setSelected(true);
        jRegValidCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegValidCheckBoxActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Search Results");

        jManufactureTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jManufactureTxtFieldActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Fleet Summary");

        jLabel4.setText("Manufacture Year");

        jLabel14.setText("Current City");

        jCurrCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCurrCityActionPerformed(evt);
            }
        });

        jLabel15.setText("Total Cars");

        jLabel5.setText("Min. Seating Capacity");

        jFleetSummary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car ID", "Make", "Model", "Capacity", "State", "Registration #", "Available?", "Available From", "Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jFleetSummary);
        if (jFleetSummary.getColumnModel().getColumnCount() > 0) {
            jFleetSummary.getColumnModel().getColumn(0).setMinWidth(0);
            jFleetSummary.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jMinSeatCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMinSeatCapActionPerformed(evt);
            }
        });

        jTotalCars.setText("jLabel17");

        jLabel6.setText("Max. Seating Capacity");

        jMaxSeatCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMaxSeatCapActionPerformed(evt);
            }
        });

        jButton2.setText("View Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Registration State");

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Fleet Details");

        jSearchButton.setText("Search");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(26, 26, 26)
                                .addComponent(jTotalCars))
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLastUpdateAt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addGap(363, 363, 363))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(26, 26, 26)
                                .addComponent(jAvailCars)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel19)
                                .addGap(26, 26, 26)
                                .addComponent(jUnavailCars)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSearchButton)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jButton2)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCurrentlyAvailableChkBox)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jModelNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jMinSeatCap, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jManufactureTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRegStateComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jRegValidCheckBox))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(11, 11, 11))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(60, 60, 60)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jRegNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(jMaxSeatCap)
                                    .addComponent(jManufactureYearTxtField)
                                    .addComponent(jCurrCity))))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTotalCars)
                    .addComponent(jLabel16)
                    .addComponent(jAvailCars)
                    .addComponent(jLabel19)
                    .addComponent(jUnavailCars))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLastUpdateAt))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jManufactureYearTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel9)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jMaxSeatCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jRegNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(jCurrCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jCurrentlyAvailableChkBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jManufactureTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jMinSeatCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRegStateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRegValidCheckBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSearchButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRegNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegNumberActionPerformed

    private void jRegStateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegStateComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegStateComboBoxActionPerformed

    private void jModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModelNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jModelNumberActionPerformed

    private void jCurrentlyAvailableChkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCurrentlyAvailableChkBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCurrentlyAvailableChkBoxActionPerformed

    private void jRegValidCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegValidCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegValidCheckBoxActionPerformed

    private void jManufactureTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jManufactureTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jManufactureTxtFieldActionPerformed

    private void jCurrCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCurrCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCurrCityActionPerformed

    private void jMinSeatCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMinSeatCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMinSeatCapActionPerformed

    private void jMaxSeatCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMaxSeatCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMaxSeatCapActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        int column = 0;
        int row = jFleetSummary.getSelectedRow();
        int carId = Integer.parseInt(jFleetSummary.getModel().getValueAt(row, column).toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        // TODO add your handling code here:
        boolean currAvail = jCurrentlyAvailableChkBox.isSelected();
        String manufacturer = jManufactureTxtField.getText();
        int manYear = jManufactureYearTxtField.getText().trim().isEmpty() ? 0 : Integer.parseInt(jManufactureYearTxtField.getText());
        String modelNumber = jModelNumber.getText();
        int maxSeatingCapacity = jMaxSeatCap.getText().trim().isEmpty() ? 0 : Integer.parseInt(jMaxSeatCap.getText());
        int minSeatingCapacity = jMinSeatCap.getText().trim().isEmpty() ? 0 : Integer.parseInt(jMinSeatCap.getText());
        String registrationState = jRegStateComboBox.getSelectedItem() != null ? jRegStateComboBox.getSelectedItem().toString() : "";
        String registrationNumber = jRegNumber.getText();
        boolean validPermit = jRegValidCheckBox.isSelected();
        String currentCity = jCurrCity.getText();

        var carList = this.carFleet.getFleet();
        DefaultTableModel model = (DefaultTableModel) jFleetSummary.getModel();
        model.setRowCount(0);
        Object rowData[] = new Object[9];
        Format f = new SimpleDateFormat("MM/dd/yy");
        for (int i = 0; i < carList.size(); i++) {
            var obj = carList.get(i);
            if (obj.getCurrentAvailability() != currAvail) {
                continue;
            }
            if (obj.getPermitValid() != validPermit) {
                continue;
            }
            if (manufacturer != null && !manufacturer.trim().isEmpty() && !manufacturer.trim().equals(obj.getManufacturerName())) {
                continue;
            }
            if (manYear > 0 && manYear != obj.getManufactureDate().getYear()) {
                continue;
            }
            if (modelNumber != null && !modelNumber.trim().isEmpty() && !modelNumber.trim().equals(obj.getModelNumber())) {
                continue;
            }
            //if(obj.getMaxSeat() < )
            if (registrationState != null && !registrationState.trim().isEmpty() && !registrationState.trim().equals(obj.getRegistrationState())) {
                continue;
            }
            if (registrationNumber != null && !registrationNumber.trim().isEmpty() && !registrationNumber.trim().equals(obj.getVehicleNumber())) {
                continue;
            }
            if (currentCity != null && !currentCity.trim().isEmpty() && !currentCity.trim().equals(obj.getCity())) {
                continue;
            }
            rowData[0] = obj.getCarID();
            rowData[1] = obj.getManufacturerName();
            rowData[2] = obj.getModelNumber();
            rowData[3] = obj.getMaxSeat();
            rowData[4] = obj.getRegistrationState();
            rowData[5] = obj.getVehicleNumber();
            rowData[6] = obj.getCurrentAvailabilityText();
            rowData[7] = obj.getCurrentAvailability() ? "" : f.format(obj.getDateFrom());
            rowData[8] = obj.getCity();
            model.addRow(rowData);
        }

    }//GEN-LAST:event_jSearchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAvailCars;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jCurrCity;
    private javax.swing.JCheckBox jCurrentlyAvailableChkBox;
    private javax.swing.JTable jFleetSummary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLastUpdateAt;
    private javax.swing.JTextField jManufactureTxtField;
    private javax.swing.JTextField jManufactureYearTxtField;
    private javax.swing.JTextField jMaxSeatCap;
    private javax.swing.JTextField jMinSeatCap;
    private javax.swing.JTextField jModelNumber;
    private javax.swing.JTextField jRegNumber;
    private javax.swing.JComboBox<String> jRegStateComboBox;
    private javax.swing.JCheckBox jRegValidCheckBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JLabel jTotalCars;
    private javax.swing.JLabel jUnavailCars;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
